[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sepawithdraw = "C1dGXHWZ1TyFQjkfQcqjsckcYuhak63X4PCn2rkXkMGL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/vhits/.config/solana/met.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
